# Generated by Django 5.0.1 on 2024-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icecream",
            name="description",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="icecream",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="icecream",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
